version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: eggheads
      MYSQL_DATABASE: eggheads
      MYSQL_USER: eggheads
      MYSQL_PASSWORD: eggheads
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
